name: Release

inputs:
  GITHUB_TOKEN:
    description: GitHub token
    required: true
  RUST_TARGET:
    description: target
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout sources
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.MATRIX_TARGET }}
    - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      with:
        prefix-key: ${{ inputs.RUST_TARGET }}
    - uses: taiki-e/upload-rust-binary-action@f391289bcff6a7f36b6301c0a74199657bbb4561 # v1.28.0
      with:
        bin: envchain
        target: ${{ inputs.RUST_TARGET }}
        archive: $bin-rs-$target-$tag
        tar: unix
        token: ${{ inputs.GITHUB_TOKEN }}
