name: Release

inputs:
  GITHUB_TOKEN:
    description: GitHub token
    required: true
  RUST_TARGET:
    description: target
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout sources
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.MATRIX_TARGET }}
    - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      with:
        prefix-key: ${{ inputs.RUST_TARGET }}
    - uses: taiki-e/upload-rust-binary-action@3962470d6e7f1993108411bc3f75a135ec67fc8c # v1.27.0
      with:
        bin: envchain
        target: ${{ inputs.RUST_TARGET }}
        archive: $bin-rs-$target-$tag
        tar: unix
        token: ${{ inputs.GITHUB_TOKEN }}
