name: Release

inputs:
  GITHUB_TOKEN:
    description: GitHub token
    required: true
  RUST_TARGET:
    description: target
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout sources
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.MATRIX_TARGET }}
    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        prefix-key: ${{ inputs.RUST_TARGET }}
    - uses: taiki-e/upload-rust-binary-action@381995c84a8e242b8736ec80211c563d7bd07ce7 # v1.28.1
      with:
        bin: envchain
        target: ${{ inputs.RUST_TARGET }}
        archive: $bin-rs-$target-$tag
        tar: unix
        token: ${{ inputs.GITHUB_TOKEN }}
