name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      tagpr_tag: steps.tagpr.outputs.tag
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-edit
        run: cargo install cargo-edit
      - uses: Swatinem/rust-cache@v2
      - uses: Songmu/tagpr@v1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Edit Cargo.toml
        run: |
          set -ex
          tag=${{ steps.tagpr.outputs.tag }}
          version=$(echo ${tag} | sed -e "s/v//")
          if [ $(yq e ".package.version" Cargo.toml) != "${version}" ]; then
            cargo set-version ${version}
            git config --local user.email github-actions[bot]@users.noreply.github.com
            git config --local user.name github-actions[bot]
            git diff
            git add Cargo.toml
            git commit -m "tagpr: Update version"
          else
            echo "Skipped"
          fi

  build-and-upload:
    runs-on: ubuntu-latest
    needs:
      - tagpr

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    steps:
      - uses: ./.github/actions/release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_TARGET: ${{ matrix.target }}
        if: "needs.tagpr.ouputs.tagpr_tag != ''"
