name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      tagpr_tag: steps.tagpr.outputs.tag
    steps:
      - uses: actions/checkout@v4
      - uses: Songmu/tagpr@v1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    runs-on: ubuntu-latest
    needs:
      - tagpr

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    steps:
      - uses: ./.github/actions/release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_TARGET: ${{ matrix.target }}
        if: "needs.tagpr.ouputs.tagpr_tag != ''"
